# Generated by Django 3.2.7 on 2022-04-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Thesis', '0001_initial'),
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='thesis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thesis.thesis'),
        ),
        migrations.AddField(
            model_name='comment',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Faculty.faculty'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thesis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thesis.thesis'),
        ),
    ]
