# Generated by Django 3.2.7 on 2022-04-07 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested_topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty')),
            ],
        ),
    ]
