# Generated by Django 3.2.7 on 2022-04-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_suggested_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggested_topics',
            name='description',
            field=models.TextField(default='No Description'),
            preserve_default=False,
        ),
    ]
