# Generated by Django 3.2.7 on 2022-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thesis', '0002_thesis_future_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=12)),
                ('name', models.TextField(null=True)),
                ('date', models.CharField(max_length=30)),
                ('link', models.TextField(null=True)),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
    ]
