# Generated by Django 3.2.7 on 2022-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thesis', '0003_conferences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conferences',
            new_name='Conference',
        ),
    ]
