# Generated by Django 3.2.7 on 2022-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thesis', '0005_alter_thesis_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
