# Generated by Django 3.2.7 on 2022-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thesis', '0006_conference_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainFreq',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DomainsTrend',
            fields=[
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
