# Generated by Django 3.2.7 on 2022-04-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rollno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=120)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
